const express = require('express')
const router = express.Router()
const {Contact} = require('../models/Contact')
const { authenticateUser } = require('../middlewares/authentication')


// router.get('/', function(req,res){ 
//    res.send('Welcome connected to DB')
// })
 //   will return all the documents in the collection  - model
 router.get('/', authenticateUser, function(req,res){ 
     Contact.find({ user: req.user._id})              // Database query  - not AJAX request - returns promises
        .then(function(contacts){
            res.send(contacts)      // id generated by DB has '_id' has property
        })
        .catch(function(err){
            res.send(err)
        })
})

// adding a record
router.post('/', authenticateUser ,function(req,res){
    const body = req.body
    const contact = new Contact(body)
    contact.user = req.user._id
    contact.save()
        .then(function(contact){
            res.send(contact)
        })
        .catch(function(err){
            res.send(err)
        })
})

// fiding a record
router.get('/:id',authenticateUser, function(req,res){
    const id = req.params.id
    Contact.findOne({
        user: req.user._id,
        _id: id
    })
        .then(function(contact){
            res.send(contact)
        })
        .catch(function(err){
            res.send(err)
        })
})

// deleting a record
router.delete('/:id',authenticateUser, function(req,res){
    const id = req.params.id
    Contact.findOneAndDelete({
        user: req.user._id,
        _id: id
    })
        .then(function(contact){
            res.send(contact)
        })
        .catch(function(err){
            res.send(err)
        })
})

// updating the record
router.put('/:id',authenticateUser, function(req,res){
    const id = req.params.id
    const body = req.body
    // findByIdAndUpadte - by default will not run validations
    // new - return the newly updated record
    // runValidators - to run validations while updating

    Contact.findOneAndUpdate({
        user: req.user._id,
        _id: id
    },{ $set: body}, {new: true, runValidoators: true})
        .then(function(contact){
            res.send(contact)
        })
        .catch(function(err){
            res.send(err)
        })
})


    module.exports = {
        contactRouter: router
    }